namespace ToolGood.ReadyGo.SqlParser
{
    public enum Token
    {
        Unknown,
        Comment,//注释
        String,//字符串
        Number,//数字
        Function,//函数
        Bracket,//括号
        Operator,//操作符
        Parameters,//参数 @ ?
        Semicolon,//分号
        Dot,//小数点
        Comma,//逗号
        Identifier,//列或表

        SELECT,
        DELETE,
        INSERT,
        UPDATE,

        FROM,
        HAVING,
        WHERE,
        ORDER,
        BY,
        GROUP,
        INTO,
        AS,

        CREATE,
        ALTER,
        DROP,
        SET,

        NULL,
        NOT,
        DISTINCT,

        TABLE,
        TABLESPACE,
        VIEW,
        SEQUENCE,
        TRIGGER,
        USER,
        INDEX,
        SESSION,
        PROCEDURE,
        FUNCTION,

        PRIMARY,
        KEY,
        DEFAULT,
        CONSTRAINT,
        CHECK,
        UNIQUE,
        FOREIGN,
        REFERENCES,

        EXPLAIN,
        FOR,
        IF,

        ALL,
        UNION,
        EXCEPT,
        INTERSECT,
        MINUS,
        INNER,
        LEFT,
        RIGHT,
        FULL,
        OUTER,
        JOIN,
        ON,
        SCHEMA,
        CAST,
        COLUMN,
        USE,
        DATABASE,
        TO,

        AND,
        OR,
        XOR,
        CASE,
        WHEN,
        THEN,
        ELSE,
        END,
        EXISTS,
        IN,

        NEW,
        ASC,
        DESC,
        IS,
        LIKE,
        ESCAPE,
        BETWEEN,
        VALUES,
        INTERVAL,

        LOCK,
        SOME,
        ANY,
        TRUNCATE,

        // mysql
        TRUE,

        FALSE,
        LIMIT,
        KILL,
        IDENTIFIED,
        PASSWORD,
        DUAL,
        BINARY,
        SHOW,
        REPLACE,

        // MySql procedure add by zz
        WHILE,

        DO,
        LEAVE,
        ITERATE,
        REPEAT,
        UNTIL,
        OPEN,
        CLOSE,
        OUT,
        INOUT,
        EXIT,
        UNDO,
        SQLSTATE,
        CONDITION,

        //postgresql
        WINDOW,

        OFFSET,
        ROW,
        ROWS,
        ONLY,
        FIRST,
        NEXT,
        FETCH,
        OF,
        SHARE,
        NOWAIT,
        RECURSIVE,
        TEMPORARY,
        TEMP,
        UNLOGGED,
        RESTART,
        IDENTITY,
        CONTINUE,
        CASCADE,
        RESTRICT,
        USING,
        CURRENT,
        RETURNING,
        COMMENT,
        OVER,
        TYPE,

        // oracle
        START,

        PRIOR,
        CONNECT,
        WITH,
        EXTRACT,
        CURSOR,
        MODEL,
        MERGE,
        MATCHED,
        ERRORS,
        REJECT,
        UNLIMITED,
        BEGIN,
        EXCLUSIVE,
        MODE,
        WAIT,
        ADVISE,
        SYSDATE,
        DECLARE,
        EXCEPTION,
        GRANT,
        REVOKE,
        LOOP,
        GOTO,
        COMMIT,
        SAVEPOINT,
        CROSS,

        PCTFREE,
        INITRANS,
        MAXTRANS,
        INITIALLY,
        ENABLE,
        DISABLE,
        SEGMENT,
        CREATION,
        IMMEDIATE,
        DEFERRED,
        STORAGE,
        MINEXTENTS,
        MAXEXTENTS,
        MAXSIZE,
        PCTINCREASE,
        FLASH_CACHE,
        CELL_FLASH_CACHE,
        KEEP,
        NONE,
        LOB,
        STORE,
        CHUNK,
        CACHE,
        NOCACHE,
        LOGGING,
        NOCOMPRESS,
        KEEP_DUPLICATES,
        EXCEPTIONS,
        PURGE,

        COMPUTE,
        ANALYZE,
        OPTIMIZE,

        // transact-sql
        TOP,

        ARRAY,
        DISTRIBUTE,

        // Oracle
        BINARY_FLOAT,

        BINARY_DOUBLE,

        // odps,hive
        PARTITION,

        PARTITIONED,
        OVERWRITE,

        // Teradata
        SEL,

        LOCKING,
        ACCESS,
        VOLATILE,
        MULTISET,
        POSITION,
        RANGE_N,
        FORMAT,
        QUALIFY,
        MOD,

        CONCAT,

        LPAREN,
        RPAREN,
        LBRACE,
        RBRACE,
        LBRACKET,
        RBRACKET,
        SEMI,
        COMMA,
        DOT,
        DOTDOT,
        DOTDOTDOT,
        EQ,
        GT,
        LT,
        BANG,
        BANGBANG,
        TILDE,
        QUES,
        COLON,
        COLONCOLON,
        COLONEQ,
        EQEQ,
        LTEQ,
        LTEQGT,
        LTGT,
        GTEQ,
        BANGEQ,
        BANGGT,
        BANGLT,
        AMPAMP,
        BARBAR,
        BARBARSLASH,
        BARSLASH,
        PLUS,
        SUB,
        SUBGT,
        SUBGTGT,
        STAR,
        SLASH,
        AMP,
        BAR,
        CARET,
        PERCENT,
        LTLT,
        GTGT,
        MONKEYS_AT,
        POUND,
        POUNDGT,
        POUNDGTGT,
    }
}