using FirebirdSql.Data.FirebirdClient;

namespace ToolGood.ReadyGo.FirebirdDbTests
{
    /// <summary>
    /// Firebird 测试数据库工厂：每个测试实例使用独立的嵌入式数据库文件，保证测试间完全隔离。
    /// 嵌入式模式（ServerType=1）需要本机安装 Firebird 嵌入式（fbclient.dll），未安装时仅能编译。
    /// </summary>
    internal sealed class FirebirdDbTestDb : IDisposable
    {
        public SqlHelper Helper { get; }

        private readonly string _dbFile;

        private static readonly object _createLock = new object();

        private FirebirdDbTestDb(SqlHelper helper, string dbFile)
        {
            Helper = helper;
            _dbFile = dbFile;
        }

        public static FirebirdDbTestDb Create()
        {
            // Firebird 嵌入式默认把 lock/trace 文件写到系统目录，这里重定向到可写目录
            var lockDir = Path.Combine(Path.GetTempPath(), "readygo_firebird_lock");
            Environment.SetEnvironmentVariable("FIREBIRD_LOCK", lockDir);
            Directory.CreateDirectory(lockDir);

            var dbFile = Path.Combine(Path.GetTempPath(), $"readygo_{Guid.NewGuid():N}.fdb");
            // 使用 NuGet 包内置的 Firebird 嵌入式客户端（firebird/win-x64/V4/fbclient.dll）
            var fbClient = Path.Combine(AppContext.BaseDirectory, "firebird", "win-x64", "V4", "fbclient.dll");
            var connStr = $"Database={dbFile};User=SYSDBA;Password=masterkey;ServerType=1;Client Library={fbClient};";
            if (File.Exists(dbFile) == false) {
                lock (_createLock) {
                    if (File.Exists(dbFile) == false) {
                        FbConnection.CreateDatabase(connStr);
                    }
                }
            }

            var helper = SqlHelperFactory.OpenDatabase(connStr, SqlType.FirebirdDb);

            // DateTime 字段插入时自动填充当前时间
            helper._Config.Insert_DateTime_Default_Now = true;

            helper.Execute(CreateUserInfoSql);
            helper.Execute(CreateSimpleUserSql);
            return new FirebirdDbTestDb(helper, dbFile);
        }

        public void Dispose()
        {
            Helper.Dispose();
            if (File.Exists(_dbFile)) {
                try {
                    File.Delete(_dbFile);
                } catch {
                    // 忽略清理失败
                }
            }
        }

        public const string CreateUserInfoSql = @"
CREATE TABLE ""UserInfo"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""Name"" VARCHAR(255) NOT NULL,
    ""Age"" INTEGER NOT NULL,
    ""Remark"" VARCHAR(4000),
    ""CreateTime"" TIMESTAMP NOT NULL,
    ""Money"" DECIMAL(18,2) NOT NULL,
    ""IsDelete"" BOOLEAN NOT NULL
);";

        public const string CreateSimpleUserSql = @"
CREATE TABLE ""SimpleUser"" (
    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""Name"" VARCHAR(255),
    ""Age"" INTEGER
);";

        /// <summary>
        /// 快速插入一条 UserInfo（CreateTime 由默认值机制填充）
        /// </summary>
        public UserInfo NewUser(string name, int age, decimal money = 0m, bool isDelete = false, string remark = null)
        {
            var u = new UserInfo { Name = name, Age = age, Remark = remark, Money = money, IsDelete = isDelete };
            Helper.Insert(u);
            return u;
        }
    }
}
