using ToolGood.ReadyGo.Gadget.TableManager.Providers;
using Xunit;

namespace ToolGood.ReadyGo.FirebirdDbTests
{
    /// <summary>
    /// FirebirdDbDatabaseProvider 生成 SQL 的正确性验证
    /// </summary>
    public class TableProviderFirebirdDbTests
    {
        [Fact]
        public void Firebird_自增主键_包含IDENTITY()
        {
            var sql = new FirebirdDbDatabaseProvider().GetTryCreateTable(typeof(Tb_Provider_AutoInc), false);

            Assert.Contains("EXECUTE BLOCK AS BEGIN", sql);
            Assert.Contains("CREATE TABLE \"Tb_Provider_Test\"(", sql);
            Assert.Contains("\"Id\" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql);
        }

        [Fact]
        public void Firebird_char映射为CHAR()
        {
            var sql = new FirebirdDbDatabaseProvider().GetTryCreateTable(typeof(Tb_Provider_AutoInc), false);
            Assert.Contains("\"Code\" CHAR(1)", sql);
        }

        [Fact]
        public void Firebird_非自增主键_不含IDENTITY()
        {
            var sql = new FirebirdDbDatabaseProvider().GetTryCreateTable(typeof(Tb_Provider_NoAutoInc), false);
            Assert.Contains("PRIMARY KEY", sql);
            Assert.DoesNotContain("IDENTITY", sql);
        }

        [Fact]
        public void Firebird_Truncate()
        {
            Assert.Equal("DELETE FROM \"Tb_Provider_Test\";",
                new FirebirdDbDatabaseProvider().GetTruncateTable(typeof(Tb_Provider_AutoInc)));

            Assert.Equal("DELETE FROM \"Tb_Any\";",
                new FirebirdDbDatabaseProvider().GetTruncateTable("Tb_Any"));
        }

        [Fact]
        public void Firebird_DropTable()
        {
            Assert.Equal("DROP TABLE \"Tb_Provider_Test\";",
                new FirebirdDbDatabaseProvider().GetDropTable(typeof(Tb_Provider_AutoInc)));

            Assert.Equal("DROP TABLE \"Tb_Any\";",
                new FirebirdDbDatabaseProvider().GetDropTable("Tb_Any"));
        }
    }
}
