<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>A high performance Micro-ORM supporting SQL Server, MySQL, Sqlite, PostgreSQL, Oracle, Firebird. Based on NPoco core with ReadyGo style API.</Description>
    <Copyright>Copyright 2016-2026 ToolGood</Copyright>
    <AssemblyTitle>ToolGood.ReadyGo</AssemblyTitle>
    <Authors>ToolGood</Authors>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <AssemblyName>ToolGood.ReadyGo</AssemblyName>
    <RootNamespace>ToolGood.ReadyGo</RootNamespace>
    <PackageId>ToolGood.ReadyGo</PackageId>
    <Version>5.0.21</Version>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>ToolGood.ReadyGo.snk</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageProjectUrl>https://github.com/toolgood/ToolGood.ReadyGo</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <Product>ToolGood.ReadyGo</Product>
    <PackageLicenseFile>License.txt</PackageLicenseFile>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>



  <ItemGroup>
    <PackageReference Condition="'$(TargetFramework)' == 'net8.0' or '$(TargetFramework)' == 'net9.0'" Include="System.Linq.Async" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="License.txt">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
