namespace ToolGood.ReadyGo.PostgreSQLTests
{
    /// <summary>
    /// PostgreSQL 测试数据库工厂。本机未配置 PostgreSQL 服务器时仅能编译。
    /// </summary>
    internal sealed class PostgreSQLTestDb : IDisposable
    {
        public SqlHelper Helper { get; }

        private PostgreSQLTestDb(SqlHelper helper)
        {
            Helper = helper;
        }

        public static PostgreSQLTestDb Create()
        {
            var connStr = "Host=127.0.0.1;Port=5432;Database=postgres;Username=postgres;Password=postgres;";
            var helper = SqlHelperFactory.OpenDatabase(connStr, SqlType.PostgreSQL);

            // DateTime 字段插入时自动填充当前时间
            helper._Config.Insert_DateTime_Default_Now = true;

            helper.Execute(CreateUserInfoSql);
            helper.Execute(CreateSimpleUserSql);
            return new PostgreSQLTestDb(helper);
        }

        public void Dispose()
        {
            Helper.Dispose();
        }

        public const string CreateUserInfoSql = @"
CREATE TABLE ""UserInfo"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""Name"" varchar(255) NOT NULL,
    ""Age"" integer NOT NULL,
    ""Remark"" varchar(4000),
    ""CreateTime"" timestamp NOT NULL,
    ""Money"" numeric(18,2) NOT NULL,
    ""IsDelete"" boolean NOT NULL
);";

        public const string CreateSimpleUserSql = @"
CREATE TABLE ""SimpleUser"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""Name"" varchar(255),
    ""Age"" integer
);";

        /// <summary>
        /// 快速插入一条 UserInfo（CreateTime 由默认值机制填充）
        /// </summary>
        public UserInfo NewUser(string name, int age, decimal money = 0m, bool isDelete = false, string remark = null)
        {
            var u = new UserInfo { Name = name, Age = age, Remark = remark, Money = money, IsDelete = isDelete };
            Helper.Insert(u);
            return u;
        }
    }
}
