namespace ToolGood.ReadyGo.OracleTests
{
    /// <summary>
    /// Oracle 测试数据库工厂。
    /// Oracle 核心层 EscapeSqlIdentifier 会把标识符转大写（"USERINFO"），因此手工建表统一使用大写表名/列名。
    /// 本机未配置 Oracle 服务器时仅能编译。
    /// </summary>
    internal sealed class OracleTestDb : IDisposable
    {
        public SqlHelper Helper { get; }

        private OracleTestDb(SqlHelper helper)
        {
            Helper = helper;
        }

        public static OracleTestDb Create()
        {
            var helper = SqlHelperFactory.OpenOracle("127.0.0.1", 1521, "ORCL", "test", "test");

            // DateTime 字段插入时自动填充当前时间
            helper._Config.Insert_DateTime_Default_Now = true;

            helper.Execute(CreateUserInfoSql);
            helper.Execute(CreateSimpleUserSql);
            return new OracleTestDb(helper);
        }

        public void Dispose()
        {
            Helper.Dispose();
        }

        public const string CreateUserInfoSql = @"
CREATE TABLE ""USERINFO"" (
    ""ID"" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""NAME"" NVARCHAR2(255) NOT NULL,
    ""AGE"" NUMBER(10) NOT NULL,
    ""REMARK"" NVARCHAR2(4000),
    ""CREATETIME"" DATE NOT NULL,
    ""MONEY"" NUMBER(19,4) NOT NULL,
    ""ISDELETE"" NUMBER(1) NOT NULL
)";

        public const string CreateSimpleUserSql = @"
CREATE TABLE ""SIMPLEUSER"" (
    ""ID"" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""NAME"" NVARCHAR2(255),
    ""AGE"" NUMBER(10)
)";

        /// <summary>
        /// 快速插入一条 UserInfo（CreateTime 由默认值机制填充）
        /// </summary>
        public UserInfo NewUser(string name, int age, decimal money = 0m, bool isDelete = false, string remark = null)
        {
            var u = new UserInfo { Name = name, Age = age, Remark = remark, Money = money, IsDelete = isDelete };
            Helper.Insert(u);
            return u;
        }
    }
}
