using ToolGood.ReadyGo.Gadget.TableManager.Providers;
using Xunit;

namespace ToolGood.ReadyGo.OracleTests
{
    /// <summary>
    /// OracleDatabaseProvider 生成 SQL 的正确性验证
    /// </summary>
    public class TableProviderOracleDbTests
    {
        [Fact]
        public void Oracle_自增主键_包含IDENTITY()
        {
            var sql = new OracleDatabaseProvider().GetTryCreateTable(typeof(Tb_Provider_AutoInc), false);

            Assert.Contains("BEGIN EXECUTE IMMEDIATE", sql);
            Assert.Contains("CREATE TABLE \"Tb_Provider_Test\"(", sql);
            Assert.Contains("\"Id\" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql);
        }

        [Fact]
        public void Oracle_char映射为CHAR()
        {
            var sql = new OracleDatabaseProvider().GetTryCreateTable(typeof(Tb_Provider_AutoInc), false);
            Assert.Contains("\"Code\" CHAR(1)", sql);
        }

        [Fact]
        public void Oracle_非自增主键_不含IDENTITY()
        {
            var sql = new OracleDatabaseProvider().GetTryCreateTable(typeof(Tb_Provider_NoAutoInc), false);
            Assert.Contains("\"Id\" NUMBER(10) NOT NULL PRIMARY KEY", sql);
            Assert.DoesNotContain("IDENTITY", sql);
        }

        [Fact]
        public void Oracle_Truncate()
        {
            Assert.Equal("TRUNCATE TABLE \"Tb_Provider_Test\";",
                new OracleDatabaseProvider().GetTruncateTable(typeof(Tb_Provider_AutoInc)));

            Assert.Equal("TRUNCATE TABLE \"Tb_Any\";",
                new OracleDatabaseProvider().GetTruncateTable("Tb_Any"));
        }

        [Fact]
        public void Oracle_DropTable()
        {
            Assert.Equal("DROP TABLE \"Tb_Provider_Test\";",
                new OracleDatabaseProvider().GetDropTable(typeof(Tb_Provider_AutoInc)));

            Assert.Equal("DROP TABLE \"Tb_Any\";",
                new OracleDatabaseProvider().GetDropTable("Tb_Any"));
        }
    }
}
